# Assignment 1 - NumPy

## 1. Create a 1D NumPy array with integers from 1 to 20

In [5]:

import numpy as np

arr = np.arange(1, 21)
print("Array:", arr)

# a. Sum, mean, median, std
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

# b. Indices of elements greater than 10
indices = np.where(arr > 10)
print("Indices of elements > 10:", indices)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


## 2. Create a 2D 4x4 NumPy array with numbers 1 to 16

In [6]:

arr2d = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr2d)

# Transpose
print("Transpose:\n", arr2d.T)

# Row-wise sums
print("Row-wise sums:", np.sum(arr2d, axis=1))

# Column-wise sums
print("Column-wise sums:", np.sum(arr2d, axis=0))


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


## 3. Create two random 3x3 arrays with integers 1 to 20

In [7]:

a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

print("Array A:\n", a)
print("Array B:\n", b)

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)

# Dot product
print("Dot Product:\n", np.dot(a, b))


Array A:
 [[ 1  3 20]
 [ 6  7 17]
 [20  9 17]]
Array B:
 [[15 17  6]
 [ 7 14 17]
 [ 7 13 10]]
Addition:
 [[16 20 26]
 [13 21 34]
 [27 22 27]]
Subtraction:
 [[-14 -14  14]
 [ -1  -7   0]
 [ 13  -4   7]]
Multiplication:
 [[ 15  51 120]
 [ 42  98 289]
 [140 117 170]]
Dot Product:
 [[176 319 257]
 [258 421 325]
 [482 687 443]]


## 4. Reshape a 1D array of size 12 into 3x4 and slice first 2 rows, last 2 columns

In [8]:

arr12 = np.arange(1, 13)
arr_reshaped = arr12.reshape(3, 4)
print("Reshaped Array:\n", arr_reshaped)

# Slice first 2 rows and last 2 columns
print("Sliced:\n", arr_reshaped[:2, -2:])


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced:
 [[3 4]
 [7 8]]
